up:
	ln ./config.fish ~/.config/fish
	cp -r ./functions ~/.config/fish/
	cp -r ./completions ~/.config/fish/
clean:
	unlink ~/.config/fish/config.fish
	rm -r ~/.config/fish/functions
	rm -r ~/.config/fish/completions
update: clean up
